import_google_font:
  default: true
  description: Если флажок не установлен, тема больше не будет включать шрифт Google Muli. Это полезно, если вы хотите определить свой собственный шрифт для темы через компонент темы.
default_light:
  default: false
  description: Если этот флажок установлен, для новых посетителей тема будет показывать светлую тему по умолчанию.